disable gphoto2 in wine32on64 due to
../../../../sources/wine/dlls/gphoto2.ds/gphoto2_main.c:72:35: error: passing 'const __storage32 char *__storage32 *' to parameter of type 'const char **' discards qualifiers in nested pointer types
      [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
        ret = gp_list_get_name (list, i, &name);
                                         ^~~~~
/usr/local/opt/libgphoto2/include/gphoto2/gphoto2-list.h:81:66: note: passing argument to parameter 'name' here
int gp_list_get_name  (CameraList *list, int index, const char **name);
                                                                 ^
../../../../sources/wine/dlls/gphoto2.ds/gphoto2_main.c:101:35: error: passing 'const __storage32 char *__storage32 *' to parameter of type 'const char **' discards qualifiers in nested pointer types
      [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
        ret = gp_list_get_name (list, i, &name);
                                         ^~~~~
/usr/local/opt/libgphoto2/include/gphoto2/gphoto2-list.h:81:66: note: passing argument to parameter 'name' here
int gp_list_get_name  (CameraList *list, int index, const char **name);
                                                                 ^
../../../../sources/wine/dlls/gphoto2.ds/gphoto2_main.c:1112:53: error: passing 'const __storage32 char *__storage32 *' to parameter of type 'const char **' discards qualifiers in nested pointer types
      [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
    gp_list_get_name  (detected_cameras, curcamera, &cname);
                                                    ^~~~~~
/usr/local/opt/libgphoto2/include/gphoto2/gphoto2-list.h:81:66: note: passing argument to parameter 'name' here
int gp_list_get_name  (CameraList *list, int index, const char **name);
                                                                 ^
../../../../sources/wine/dlls/gphoto2.ds/gphoto2_main.c:1113:53: error: passing 'const __storage32 char *__storage32 *' to parameter of type 'const char **' discards qualifiers in nested pointer types
      [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
    gp_list_get_value (detected_cameras, curcamera, &pname);
                                                    ^~~~~~
/usr/local/opt/libgphoto2/include/gphoto2/gphoto2-list.h:82:66: note: passing argument to parameter 'value' here
int gp_list_get_value (CameraList *list, int index, const char **value);
                                                                 ^
../../../../sources/wine/dlls/gphoto2.ds/gphoto2_main.c:1165:46: error: passing 'const __storage32 char *__storage32 *' to parameter of type 'const char **' discards qualifiers in nested pointer types
      [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
            gp_list_get_name  (detected_cameras, i, &cname);
                                                    ^~~~~~
/usr/local/opt/libgphoto2/include/gphoto2/gphoto2-list.h:81:66: note: passing argument to parameter 'name' here
int gp_list_get_name  (CameraList *list, int index, const char **name);
                                                                 ^
../../../../sources/wine/dlls/gphoto2.ds/gphoto2_main.c:1166:46: error: passing 'const __storage32 char *__storage32 *' to parameter of type 'const char **' discards qualifiers in nested pointer types
      [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
            gp_list_get_value (detected_cameras, i, &pname);
                                                    ^~~~~~
/usr/local/opt/libgphoto2/include/gphoto2/gphoto2-list.h:82:66: note: passing argument to parameter 'value' here
int gp_list_get_value (CameraList *list, int index, const char **value);
                                                                 ^
../../../../sources/wine/dlls/gphoto2.ds/gphoto2_main.c:1181:45: error: passing 'const __storage32 char *__storage32 *' to parameter of type 'const char **' discards qualifiers in nested pointer types
      [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
    gp_list_get_name  (detected_cameras, i, &model);
                                            ^~~~~~
/usr/local/opt/libgphoto2/include/gphoto2/gphoto2-list.h:81:66: note: passing argument to parameter 'name' here
int gp_list_get_name  (CameraList *list, int index, const char **name);
                                                                 ^
../../../../sources/wine/dlls/gphoto2.ds/gphoto2_main.c:1182:46: error: passing 'const __storage32 char *__storage32 *' to parameter of type 'const char **' discards qualifiers in nested pointer types
      [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
    gp_list_get_value  (detected_cameras, i, &port);
                                             ^~~~~
/usr/local/opt/libgphoto2/include/gphoto2/gphoto2-list.h:82:66: note: passing argument to parameter 'value' here
int gp_list_get_value (CameraList *list, int index, const char **value);
                                                                 ^
8 errors generated.